### PR TITLE
Support stored procedure.

### PR DESCRIPTION
**Pull request by yihuang**
It don't break exist tests, and pass the test i add for stored procedure.
The first commit is a hexdump utility i use to solve this problem, if you don't like it, you can just pick the rest commits (the second commit is the changes need to support stored procedure, the third one is the test).

### CODE REVIEW

**Comment by jskorpan** [comment]
Thanks for the contribution!

Are there any other UltraMySQL users that could take part in validating and expanding on this patch?

Sadly I have no experience what so ever with Stored Procedures.

//JT

**Comment by mthurlin** [comment]
@yihuang Your patch only sets the MULTI_RESULT protocol flag, does ultramysql really support multiple result sets?
Your tests does not test this, so I would like a test with the following stored procedure:

```
DELIMITER //
CREATE PROCEDURE TestMultiResult()
BEGIN
    SELECT 1;
    SELECT 2;
    SELECT 3;
END //
DELIMITER ;
```

Will it return three result sets correctly?

**Comment by yihuang** [comment]
Yes, it don't really support MULTI_RESULT, but i can try to implement this feature in following days.
I don't have much experiences at mysql protocol, any suggestion would be appreciated.

**Comment by jskorpan** [comment]
Sounds awesome, keep us posted!

**Comment by yihuang** [comment]
It's done.
It needs server support CLIENT_PROTOCOL_41, the code don't check that, because existing code seems assuming that already.

**Comment by jskorpan** [comment]
Hi, sorry for the slow response.
I've merged your pull request into a separate branch. Such a big feature addition should be taken slowly and must be thorowly tested.

Thanks for your awesome contribution!

**Pull request closed without merging**
